export interface Bairro {
  nome: string;
  cep: string;
  tipo: "urbano" | "rural";
}

export interface Rua {
  nome: string;
  bairro: string;
  cep: string;
}

export interface CityData {
  id: string;
  nome: string;
  estado: string;
  sigla: string;
  populacao: number;
  area: number;
  altitude: number;
  fundacao: string;
  coordenadas: [number, number];
  zoom: number;
  descricao: string;
  gentilico: string;
  prefeito: string;
  prefeituraUrl: string;
  prefeituraTelefone: string;
  prefeituraEmail: string;
  prefeituraHorario: string;
  prefeituraEndereco: string;
  prefeituraCnpj: string;
  brasaoUrl?: string;
  bairros: Bairro[];
  ruasPrincipais: Rua[];
  distritos: string[];
}

export const cities: CityData[] = [
  {
    id: "itapipoca-ce",
    nome: "Itapipoca",
    estado: "Ceará",
    sigla: "CE",
    populacao: 131077,
    area: 1614.28,
    altitude: 109,
    fundacao: "1823",
    coordenadas: [-3.4944, -39.5833],
    zoom: 13,
    descricao: "Itapipoca é um município brasileiro do estado do Ceará, conhecida como 'Terra da Pedra que Ronca'. É o 8º município mais populoso do Ceará, com forte tradição cultural e econômica baseada na agricultura, pecuária e comércio.",
    gentilico: "Itapipoquense",
    prefeito: "Felipe Pinheiro",
    prefeituraUrl: "https://www.itapipoca.ce.gov.br",
    prefeituraTelefone: "(88) 3631-0707",
    prefeituraEmail: "gabinete@itapipoca.ce.gov.br",
    prefeituraHorario: "Seg a Sex, 8h às 14h",
    prefeituraEndereco: "Rua Coronel Meireles, S/N - Centro, Itapipoca - CE",
    prefeituraCnpj: "07.623.077/0001-44",
    brasaoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Bras%C3%A3o_de_Itapipoca.png/150px-Bras%C3%A3o_de_Itapipoca.png",
    bairros: [
      { nome: "Centro", cep: "62500-000", tipo: "urbano" },
      { nome: "São Sebastião", cep: "62500-000", tipo: "urbano" },
      { nome: "Nossa Senhora das Graças", cep: "62500-000", tipo: "urbano" },
      { nome: "Cohab", cep: "62500-000", tipo: "urbano" },
      { nome: "Violete", cep: "62500-000", tipo: "urbano" },
      { nome: "Alto do Cristo", cep: "62500-000", tipo: "urbano" },
      { nome: "Boa Vista", cep: "62500-000", tipo: "urbano" },
      { nome: "Caiçara", cep: "62500-000", tipo: "urbano" },
      { nome: "São José", cep: "62500-000", tipo: "urbano" },
      { nome: "Bela Vista", cep: "62500-000", tipo: "urbano" },
      { nome: "Fazendinha", cep: "62500-000", tipo: "urbano" },
      { nome: "Olho d'Água", cep: "62500-000", tipo: "urbano" },
      { nome: "Alto Alegre", cep: "62500-000", tipo: "urbano" },
      { nome: "Ladeira Grande", cep: "62500-000", tipo: "urbano" },
      { nome: "Recanto", cep: "62500-000", tipo: "urbano" },
      { nome: "Assunção", cep: "62505-000", tipo: "rural" },
      { nome: "Baleia", cep: "62518-000", tipo: "rural" },
      { nome: "Barrento", cep: "62515-000", tipo: "rural" },
      { nome: "Deserto", cep: "62514-000", tipo: "rural" },
      { nome: "Marinheiros", cep: "62520-000", tipo: "rural" },
      { nome: "Arapari", cep: "62508-000", tipo: "rural" },
      { nome: "Ipu-Mazagão", cep: "62500-000", tipo: "rural" },
      { nome: "Cruxati", cep: "62525-000", tipo: "rural" },
      { nome: "Lagoa das Mercês", cep: "62500-000", tipo: "rural" },
      { nome: "Mourão", cep: "62500-000", tipo: "rural" },
    ],
    ruasPrincipais: [
      { nome: "Rua Coronel Meireles", bairro: "Centro", cep: "62500-000" },
      { nome: "Rua Major Raimundo", bairro: "Centro", cep: "62500-000" },
      { nome: "Avenida Monsenhor Tabosa", bairro: "Centro", cep: "62500-000" },
      { nome: "Rua Dr. José Pontes", bairro: "Centro", cep: "62500-000" },
      { nome: "Rua do Comércio", bairro: "Centro", cep: "62500-000" },
      { nome: "Travessa São Pedro", bairro: "Centro", cep: "62500-000" },
      { nome: "Rua Padre Ibiapina", bairro: "São Sebastião", cep: "62500-010" },
      { nome: "Rua São Francisco", bairro: "São Sebastião", cep: "62500-010" },
      { nome: "Rua da Igreja", bairro: "São Sebastião", cep: "62500-010" },
      { nome: "Rua Maria Tomásia", bairro: "Nossa Senhora das Graças", cep: "62500-020" },
      { nome: "Rua Nossa Senhora Aparecida", bairro: "Nossa Senhora das Graças", cep: "62500-020" },
      { nome: "Avenida da Integração", bairro: "Cohab", cep: "62500-030" },
      { nome: "Rua das Flores", bairro: "Cohab", cep: "62500-030" },
      { nome: "Rua Principal", bairro: "Cohab", cep: "62500-030" },
      { nome: "Rua do Violete", bairro: "Violete", cep: "62500-040" },
      { nome: "Rua Nova", bairro: "Violete", cep: "62500-040" },
      { nome: "Rua do Cruzeiro", bairro: "Alto do Cristo", cep: "62500-050" },
      { nome: "Rua da Ladeira", bairro: "Alto do Cristo", cep: "62500-050" },
      { nome: "Rua Boa Vista", bairro: "Boa Vista", cep: "62500-060" },
      { nome: "Rua do Sol", bairro: "Boa Vista", cep: "62500-060" },
      { nome: "Rua da Caiçara", bairro: "Caiçara", cep: "62500-070" },
      { nome: "Rua Projetada A", bairro: "Caiçara", cep: "62500-070" },
      { nome: "Rua São José", bairro: "São José", cep: "62500-080" },
      { nome: "Rua da Esperança", bairro: "São José", cep: "62500-080" },
      { nome: "Rua Bela Vista", bairro: "Bela Vista", cep: "62500-090" },
      { nome: "Rua do Mirante", bairro: "Bela Vista", cep: "62500-090" },
      { nome: "Rua da Fazendinha", bairro: "Fazendinha", cep: "62500-100" },
      { nome: "Rua Olho d'Água", bairro: "Olho d'Água", cep: "62500-110" },
      { nome: "Rua Alto Alegre", bairro: "Alto Alegre", cep: "62500-120" },
      { nome: "Rua da Ladeira Grande", bairro: "Ladeira Grande", cep: "62500-130" },
      { nome: "Rua do Recanto", bairro: "Recanto", cep: "62500-140" },
    ],
    distritos: ["Arapari", "Assunção", "Baleia", "Barrento", "Deserto", "Marinheiros", "Ipu-Mazagão"],
  },
  {
    id: "fortaleza-ce",
    nome: "Fortaleza",
    estado: "Ceará",
    sigla: "CE",
    populacao: 2703391,
    area: 312.4,
    altitude: 21,
    fundacao: "1726",
    coordenadas: [-3.7172, -38.5433],
    zoom: 12,
    descricao: "Capital do estado do Ceará, Fortaleza é a 5ª cidade mais populosa do Brasil. Conhecida por suas praias, cultura vibrante e gastronomia típica nordestina.",
    gentilico: "Fortalezense",
    prefeito: "José Sarto",
    prefeituraUrl: "https://www.fortaleza.ce.gov.br",
    prefeituraTelefone: "(85) 3452-3477",
    prefeituraEmail: "gabinete@fortaleza.ce.gov.br",
    prefeituraHorario: "Seg a Sex, 8h às 17h",
    prefeituraEndereco: "Rua São José, 1 - Centro, Fortaleza - CE",
    prefeituraCnpj: "07.954.605/0001-60",
    brasaoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Bras%C3%A3o_de_Fortaleza.svg/150px-Bras%C3%A3o_de_Fortaleza.svg.png",
    bairros: [
      { nome: "Centro", cep: "60000-000", tipo: "urbano" },
      { nome: "Aldeota", cep: "60140-000", tipo: "urbano" },
      { nome: "Meireles", cep: "60165-000", tipo: "urbano" },
      { nome: "Praia de Iracema", cep: "60060-000", tipo: "urbano" },
      { nome: "Benfica", cep: "60020-000", tipo: "urbano" },
      { nome: "Fátima", cep: "60040-000", tipo: "urbano" },
      { nome: "Mucuripe", cep: "60175-000", tipo: "urbano" },
      { nome: "Varjota", cep: "60175-100", tipo: "urbano" },
      { nome: "Papicu", cep: "60175-200", tipo: "urbano" },
      { nome: "Cocó", cep: "60190-000", tipo: "urbano" },
      { nome: "Dionísio Torres", cep: "60135-000", tipo: "urbano" },
      { nome: "Joaquim Távora", cep: "60110-000", tipo: "urbano" },
      { nome: "José Bonifácio", cep: "60050-000", tipo: "urbano" },
      { nome: "Jacarecanga", cep: "60010-000", tipo: "urbano" },
      { nome: "Monte Castelo", cep: "60325-000", tipo: "urbano" },
      { nome: "Parquelândia", cep: "60450-000", tipo: "urbano" },
      { nome: "Presidente Kennedy", cep: "60355-000", tipo: "urbano" },
      { nome: "Barra do Ceará", cep: "60330-000", tipo: "urbano" },
      { nome: "Pirambu", cep: "60310-000", tipo: "urbano" },
      { nome: "Cristo Redentor", cep: "60340-000", tipo: "urbano" },
      { nome: "Messejana", cep: "60840-000", tipo: "urbano" },
      { nome: "Parangaba", cep: "60740-000", tipo: "urbano" },
      { nome: "Montese", cep: "60410-000", tipo: "urbano" },
      { nome: "Edson Queiroz", cep: "60811-000", tipo: "urbano" },
      { nome: "Cambeba", cep: "60822-000", tipo: "urbano" },
      { nome: "Água Fria", cep: "60810-000", tipo: "urbano" },
      { nome: "Maraponga", cep: "60710-000", tipo: "urbano" },
      { nome: "Mondubim", cep: "60760-000", tipo: "urbano" },
      { nome: "Passaré", cep: "60861-000", tipo: "urbano" },
      { nome: "Cajazeiras", cep: "60864-000", tipo: "urbano" },
    ],
    ruasPrincipais: [
      { nome: "Avenida Beira Mar", bairro: "Meireles", cep: "60165-000" },
      { nome: "Rua Ana Bilhar", bairro: "Meireles", cep: "60165-050" },
      { nome: "Rua Ildefonso Albano", bairro: "Meireles", cep: "60165-030" },
      { nome: "Rua Barão de Studart", bairro: "Aldeota", cep: "60140-000" },
      { nome: "Rua Torres Câmara", bairro: "Aldeota", cep: "60140-100" },
      { nome: "Rua Nogueira Acioly", bairro: "Aldeota", cep: "60140-200" },
      { nome: "Avenida Monsenhor Tabosa", bairro: "Praia de Iracema", cep: "60060-000" },
      { nome: "Rua dos Tabajaras", bairro: "Praia de Iracema", cep: "60060-100" },
      { nome: "Rua dos Tremembés", bairro: "Praia de Iracema", cep: "60060-200" },
      { nome: "Avenida Santos Dumont", bairro: "Aldeota", cep: "60150-000" },
      { nome: "Avenida Dom Manuel", bairro: "Centro", cep: "60000-100" },
      { nome: "Rua Guilherme Rocha", bairro: "Centro", cep: "60000-200" },
      { nome: "Rua Senador Pompeu", bairro: "Centro", cep: "60000-300" },
      { nome: "Rua Major Facundo", bairro: "Centro", cep: "60000-400" },
      { nome: "Rua Floriano Peixoto", bairro: "Centro", cep: "60000-500" },
      { nome: "Avenida da Universidade", bairro: "Benfica", cep: "60020-100" },
      { nome: "Rua Marechal Deodoro", bairro: "Benfica", cep: "60020-200" },
      { nome: "Avenida 13 de Maio", bairro: "Fátima", cep: "60040-100" },
      { nome: "Rua Barão do Rio Branco", bairro: "Fátima", cep: "60040-200" },
      { nome: "Avenida Abolição", bairro: "Mucuripe", cep: "60175-050" },
      { nome: "Rua Frei Mansueto", bairro: "Varjota", cep: "60175-110" },
      { nome: "Avenida Engenheiro Santana Jr", bairro: "Cocó", cep: "60190-100" },
      { nome: "Rua Barbosa de Freitas", bairro: "Dionísio Torres", cep: "60135-100" },
      { nome: "Avenida Bezerra de Menezes", bairro: "Monte Castelo", cep: "60325-100" },
      { nome: "Avenida José Bastos", bairro: "Montese", cep: "60410-100" },
      { nome: "Avenida Godofredo Maciel", bairro: "Maraponga", cep: "60710-100" },
      { nome: "Avenida Washington Soares", bairro: "Edson Queiroz", cep: "60811-100" },
      { nome: "Rua Israel Bezerra", bairro: "Dionísio Torres", cep: "60135-200" },
      { nome: "Avenida Aguanambi", bairro: "Joaquim Távora", cep: "60110-100" },
      { nome: "Rua Pereira de Miranda", bairro: "Papicu", cep: "60175-210" },
    ],
    distritos: [],
  },
  {
    id: "sobral-ce",
    nome: "Sobral",
    estado: "Ceará",
    sigla: "CE",
    populacao: 212437,
    area: 2122.98,
    altitude: 70,
    fundacao: "1841",
    coordenadas: [-3.6861, -40.3481],
    zoom: 13,
    descricao: "Sobral é a segunda maior cidade do interior do Ceará. Conhecida por seu centro histórico preservado e pela comprovação da Teoria da Relatividade de Einstein em 1919.",
    gentilico: "Sobralense",
    prefeito: "Oscar Rodrigues",
    prefeituraUrl: "https://www.sobral.ce.gov.br",
    prefeituraTelefone: "(88) 3677-1157",
    prefeituraEmail: "gabinete@sobral.ce.gov.br",
    prefeituraHorario: "Seg a Sex, 8h às 14h",
    prefeituraEndereco: "Rua Viriato de Medeiros, 1250 - Centro, Sobral - CE",
    prefeituraCnpj: "07.598.634/0001-37",
    brasaoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Bras%C3%A3o_de_Sobral_%28Cear%C3%A1%29.png/150px-Bras%C3%A3o_de_Sobral_%28Cear%C3%A1%29.png",
    bairros: [
      { nome: "Centro", cep: "62010-000", tipo: "urbano" },
      { nome: "Dom Expedito", cep: "62050-000", tipo: "urbano" },
      { nome: "Junco", cep: "62030-000", tipo: "urbano" },
      { nome: "Derby Clube", cep: "62040-000", tipo: "urbano" },
      { nome: "Sinhá Sabóia", cep: "62050-000", tipo: "urbano" },
      { nome: "Campos dos Velhos", cep: "62030-000", tipo: "urbano" },
      { nome: "Sumaré", cep: "62020-000", tipo: "urbano" },
      { nome: "Alto do Cristo", cep: "62021-000", tipo: "urbano" },
      { nome: "Expectativa", cep: "62022-000", tipo: "urbano" },
      { nome: "Padre Palhano", cep: "62023-000", tipo: "urbano" },
      { nome: "Dom José", cep: "62024-000", tipo: "urbano" },
      { nome: "Cohab I", cep: "62025-000", tipo: "urbano" },
      { nome: "Cohab II", cep: "62026-000", tipo: "urbano" },
      { nome: "Terrenos Novos", cep: "62027-000", tipo: "urbano" },
      { nome: "Alto da Brasília", cep: "62028-000", tipo: "urbano" },
      { nome: "Pedrinhas", cep: "62029-000", tipo: "urbano" },
      { nome: "Vila União", cep: "62021-000", tipo: "urbano" },
      { nome: "Coelce", cep: "62032-000", tipo: "urbano" },
      { nome: "Aracatiaçu", cep: "62111-000", tipo: "rural" },
      { nome: "Bonfim", cep: "62102-000", tipo: "rural" },
      { nome: "Caracará", cep: "62112-000", tipo: "rural" },
      { nome: "Caioca", cep: "62109-000", tipo: "rural" },
      { nome: "Jordão", cep: "62108-000", tipo: "rural" },
      { nome: "Patriarca", cep: "62104-000", tipo: "rural" },
      { nome: "Rafael Arruda", cep: "62113-000", tipo: "rural" },
      { nome: "Taperuaba", cep: "62106-000", tipo: "rural" },
    ],
    ruasPrincipais: [
      { nome: "Rua Coronel José Sabóia", bairro: "Centro", cep: "62010-000" },
      { nome: "Boulevard do Arco", bairro: "Centro", cep: "62010-100" },
      { nome: "Rua Ernesto Deocleciano", bairro: "Centro", cep: "62010-200" },
      { nome: "Rua Cel. Mont'Alverne", bairro: "Centro", cep: "62010-300" },
      { nome: "Rua Viriato de Medeiros", bairro: "Centro", cep: "62010-400" },
      { nome: "Travessa Sinval Brandão", bairro: "Centro", cep: "62010-500" },
      { nome: "Avenida John Sanford", bairro: "Junco", cep: "62030-000" },
      { nome: "Rua Conselheiro Rodrigues Jr", bairro: "Junco", cep: "62030-100" },
      { nome: "Rua Dom José Tupinambá da Frota", bairro: "Dom Expedito", cep: "62050-100" },
      { nome: "Rua Padre Linhares", bairro: "Dom Expedito", cep: "62050-200" },
      { nome: "Avenida Dr. Guarani", bairro: "Derby Clube", cep: "62040-100" },
      { nome: "Rua Maria Madalena", bairro: "Derby Clube", cep: "62040-200" },
      { nome: "Rua Sinhá Sabóia", bairro: "Sinhá Sabóia", cep: "62050-110" },
      { nome: "Rua Dr. Monte", bairro: "Sinhá Sabóia", cep: "62050-120" },
      { nome: "Rua dos Campos", bairro: "Campos dos Velhos", cep: "62011-100" },
      { nome: "Rua do Sumaré", bairro: "Sumaré", cep: "62020-100" },
      { nome: "Rua do Cristo", bairro: "Alto do Cristo", cep: "62021-100" },
      { nome: "Rua da Expectativa", bairro: "Expectativa", cep: "62022-100" },
      { nome: "Avenida Padre Palhano", bairro: "Padre Palhano", cep: "62023-100" },
      { nome: "Rua Dom José", bairro: "Dom José", cep: "62024-100" },
      { nome: "Rua Principal Cohab I", bairro: "Cohab I", cep: "62025-100" },
      { nome: "Rua Principal Cohab II", bairro: "Cohab II", cep: "62026-100" },
      { nome: "Rua dos Terrenos Novos", bairro: "Terrenos Novos", cep: "62027-100" },
      { nome: "Rua Alto da Brasília", bairro: "Alto da Brasília", cep: "62028-100" },
      { nome: "Rua das Pedrinhas", bairro: "Pedrinhas", cep: "62029-100" },
      { nome: "Rua Vila União", bairro: "Vila União", cep: "62031-100" },
    ],
    distritos: ["Aracatiaçu", "Bonfim", "Caracará", "Caioca", "Jordão", "Patriarca", "Rafael Arruda", "Taperuaba"],
  },
  {
    id: "juazeiro-do-norte-ce",
    nome: "Juazeiro do Norte",
    estado: "Ceará",
    sigla: "CE",
    populacao: 278264,
    area: 248.83,
    altitude: 377,
    fundacao: "1911",
    coordenadas: [-7.2131, -39.3151],
    zoom: 13,
    descricao: "Juazeiro do Norte é a maior cidade do interior do Ceará e importante centro religioso, conhecido pelas romarias ao Padre Cícero. Polo econômico e cultural do Cariri cearense.",
    gentilico: "Juazeirense",
    prefeito: "Glêdson Bezerra",
    prefeituraUrl: "https://www.juazeiro.ce.gov.br",
    prefeituraTelefone: "(88) 3566-8550",
    prefeituraEmail: "gabinete@juazeiro.ce.gov.br",
    prefeituraHorario: "Seg a Sex, 8h às 14h",
    prefeituraEndereco: "Rua São Pedro, S/N - Centro, Juazeiro do Norte - CE",
    prefeituraCnpj: "07.414.003/0001-07",
    brasaoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Bras%C3%A3o_de_Juazeiro_do_Norte.png/150px-Bras%C3%A3o_de_Juazeiro_do_Norte.png",
    bairros: [
      { nome: "Centro", cep: "63010-000", tipo: "urbano" },
      { nome: "São Miguel", cep: "63020-000", tipo: "urbano" },
      { nome: "Pirajá", cep: "63030-000", tipo: "urbano" },
      { nome: "Lagoa Seca", cep: "63040-000", tipo: "urbano" },
      { nome: "Salesianos", cep: "63050-000", tipo: "urbano" },
      { nome: "Tiradentes", cep: "63011-000", tipo: "urbano" },
      { nome: "Limoeiro", cep: "63012-000", tipo: "urbano" },
      { nome: "Triângulo", cep: "63013-000", tipo: "urbano" },
      { nome: "Romeirão", cep: "63014-000", tipo: "urbano" },
      { nome: "São José", cep: "63015-000", tipo: "urbano" },
      { nome: "Fátima", cep: "63016-000", tipo: "urbano" },
      { nome: "Franciscanos", cep: "63017-000", tipo: "urbano" },
      { nome: "Aeroporto", cep: "63018-000", tipo: "urbano" },
      { nome: "João Cabral", cep: "63019-000", tipo: "urbano" },
      { nome: "Horto", cep: "63021-000", tipo: "urbano" },
      { nome: "Pio XII", cep: "63022-000", tipo: "urbano" },
      { nome: "Leandro Bezerra", cep: "63023-000", tipo: "urbano" },
      { nome: "Frei Damião", cep: "63024-000", tipo: "urbano" },
      { nome: "Jardim Gonzaga", cep: "63025-000", tipo: "urbano" },
      { nome: "Novo Juazeiro", cep: "63026-000", tipo: "urbano" },
      { nome: "Timbaúba", cep: "63050-000", tipo: "rural" },
      { nome: "Palmeirinha", cep: "63050-000", tipo: "rural" },
      { nome: "Marrocos", cep: "63084-000", tipo: "rural" },
      { nome: "Padre Cícero", cep: "63082-000", tipo: "rural" },
      { nome: "Baixio das Palmeiras", cep: "63050-000", tipo: "rural" },
    ],
    ruasPrincipais: [
      { nome: "Rua São Pedro", bairro: "Centro", cep: "63010-000" },
      { nome: "Rua Santa Luzia", bairro: "Centro", cep: "63010-100" },
      { nome: "Rua do Cruzeiro", bairro: "Centro", cep: "63010-200" },
      { nome: "Avenida Padre Cícero", bairro: "Centro", cep: "63010-300" },
      { nome: "Rua São Francisco", bairro: "São Miguel", cep: "63020-100" },
      { nome: "Rua Delmiro Gouveia", bairro: "São Miguel", cep: "63020-200" },
      { nome: "Rua do Pirajá", bairro: "Pirajá", cep: "63030-100" },
      { nome: "Rua José Marrocos", bairro: "Pirajá", cep: "63030-200" },
      { nome: "Avenida Leão Sampaio", bairro: "Lagoa Seca", cep: "63040-100" },
      { nome: "Rua da Lagoa", bairro: "Lagoa Seca", cep: "63040-200" },
      { nome: "Rua Dom Bosco", bairro: "Salesianos", cep: "63050-100" },
      { nome: "Rua Tiradentes", bairro: "Tiradentes", cep: "63011-100" },
      { nome: "Rua do Limoeiro", bairro: "Limoeiro", cep: "63012-100" },
      { nome: "Rua do Triângulo", bairro: "Triângulo", cep: "63013-100" },
      { nome: "Rua dos Romeiros", bairro: "Romeirão", cep: "63014-100" },
      { nome: "Rua São José", bairro: "São José", cep: "63015-100" },
      { nome: "Rua Nossa Senhora de Fátima", bairro: "Fátima", cep: "63016-100" },
      { nome: "Rua São Francisco de Assis", bairro: "Franciscanos", cep: "63017-100" },
      { nome: "Rua do Aeroporto", bairro: "Aeroporto", cep: "63018-100" },
      { nome: "Rua João Cabral", bairro: "João Cabral", cep: "63019-100" },
      { nome: "Rua do Horto", bairro: "Horto", cep: "63021-100" },
      { nome: "Rua Pio XII", bairro: "Pio XII", cep: "63022-100" },
      { nome: "Rua Leandro Bezerra", bairro: "Leandro Bezerra", cep: "63023-100" },
      { nome: "Rua Frei Damião", bairro: "Frei Damião", cep: "63024-100" },
      { nome: "Rua do Gonzaga", bairro: "Jardim Gonzaga", cep: "63025-100" },
    ],
    distritos: ["Padre Cícero", "Palmeirinha", "Marrocos", "Timbaúba"],
  },
  {
    id: "crato-ce",
    nome: "Crato",
    estado: "Ceará",
    sigla: "CE",
    populacao: 133913,
    area: 1176.47,
    altitude: 426,
    fundacao: "1764",
    coordenadas: [-7.2342, -39.4113],
    zoom: 13,
    descricao: "Crato é conhecida como a 'Princesa do Cariri'. Abriga parte da Floresta Nacional do Araripe e o Geopark Araripe, primeiro geoparque das Américas reconhecido pela UNESCO.",
    gentilico: "Cratense",
    prefeito: "José Ailton Brasil",
    prefeituraUrl: "https://www.crato.ce.gov.br",
    prefeituraTelefone: "(88) 3521-4011",
    prefeituraEmail: "gabinete@crato.ce.gov.br",
    prefeituraHorario: "Seg a Sex, 8h às 14h",
    prefeituraEndereco: "Rua Dr. João Pessoa, S/N - Centro, Crato - CE",
    prefeituraCnpj: "07.535.446/0001-58",
    brasaoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Bras%C3%A3o_do_Crato_%28Cear%C3%A1%29.png/150px-Bras%C3%A3o_do_Crato_%28Cear%C3%A1%29.png",
    bairros: [
      { nome: "Centro", cep: "63100-000", tipo: "urbano" },
      { nome: "Pimenta", cep: "63110-000", tipo: "urbano" },
      { nome: "Seminário", cep: "63111-000", tipo: "urbano" },
      { nome: "Granjeiro", cep: "63112-000", tipo: "urbano" },
      { nome: "Batateira", cep: "63113-000", tipo: "urbano" },
      { nome: "Lameiro", cep: "63114-000", tipo: "urbano" },
      { nome: "São Miguel", cep: "63115-000", tipo: "urbano" },
      { nome: "Muriti", cep: "63116-000", tipo: "urbano" },
      { nome: "Vila Alta", cep: "63117-000", tipo: "urbano" },
      { nome: "Sossego", cep: "63118-000", tipo: "urbano" },
      { nome: "Caixa D'Água", cep: "63119-000", tipo: "urbano" },
      { nome: "Novo Crato", cep: "63120-000", tipo: "urbano" },
      { nome: "São Bento", cep: "63121-000", tipo: "urbano" },
      { nome: "Mirandão", cep: "63122-000", tipo: "urbano" },
      { nome: "Independência", cep: "63123-000", tipo: "urbano" },
      { nome: "Gizélia Pinheiro", cep: "63124-000", tipo: "urbano" },
      { nome: "Santa Luzia", cep: "63125-000", tipo: "urbano" },
      { nome: "Palmeiral", cep: "63126-000", tipo: "urbano" },
      { nome: "Dom Quintino", cep: "63122-000", tipo: "rural" },
      { nome: "Monte Alverne", cep: "63123-000", tipo: "rural" },
      { nome: "Baixio das Palmeiras", cep: "63124-000", tipo: "rural" },
      { nome: "Campo Alegre", cep: "63125-000", tipo: "rural" },
      { nome: "Santa Fé", cep: "63126-000", tipo: "rural" },
    ],
    ruasPrincipais: [
      { nome: "Rua Dr. João Pessoa", bairro: "Centro", cep: "63100-000" },
      { nome: "Rua Senador Pompeu", bairro: "Centro", cep: "63100-100" },
      { nome: "Rua Bárbara de Alencar", bairro: "Centro", cep: "63100-200" },
      { nome: "Rua Pedro Augusto", bairro: "Centro", cep: "63100-300" },
      { nome: "Rua da Pimenta", bairro: "Pimenta", cep: "63110-100" },
      { nome: "Rua Tristão Gonçalves", bairro: "Pimenta", cep: "63110-200" },
      { nome: "Rua do Seminário", bairro: "Seminário", cep: "63111-100" },
      { nome: "Rua do Granjeiro", bairro: "Granjeiro", cep: "63112-100" },
      { nome: "Rua da Batateira", bairro: "Batateira", cep: "63113-100" },
      { nome: "Rua Fonte da Batateira", bairro: "Batateira", cep: "63113-200" },
      { nome: "Rua do Lameiro", bairro: "Lameiro", cep: "63114-100" },
      { nome: "Rua São Miguel", bairro: "São Miguel", cep: "63115-100" },
      { nome: "Rua do Muriti", bairro: "Muriti", cep: "63116-100" },
      { nome: "Rua da Vila Alta", bairro: "Vila Alta", cep: "63117-100" },
      { nome: "Rua do Sossego", bairro: "Sossego", cep: "63118-100" },
      { nome: "Rua da Caixa D'Água", bairro: "Caixa D'Água", cep: "63119-100" },
      { nome: "Avenida Perimetral", bairro: "Novo Crato", cep: "63120-100" },
      { nome: "Rua São Bento", bairro: "São Bento", cep: "63121-100" },
      { nome: "Rua do Mirandão", bairro: "Mirandão", cep: "63122-100" },
      { nome: "Rua da Independência", bairro: "Independência", cep: "63123-100" },
      { nome: "Rua Gizélia Pinheiro", bairro: "Gizélia Pinheiro", cep: "63124-100" },
      { nome: "Rua Santa Luzia", bairro: "Santa Luzia", cep: "63125-100" },
      { nome: "Rua do Palmeiral", bairro: "Palmeiral", cep: "63126-100" },
    ],
    distritos: ["Dom Quintino", "Monte Alverne", "Baixio das Palmeiras", "Campo Alegre", "Santa Fé"],
  },
  {
    id: "caucaia-ce",
    nome: "Caucaia",
    estado: "Ceará",
    sigla: "CE",
    populacao: 365212,
    area: 1228.51,
    altitude: 30,
    fundacao: "1759",
    coordenadas: [-3.7361, -38.6531],
    zoom: 12,
    descricao: "Caucaia é o segundo município mais populoso do Ceará, integrando a Região Metropolitana de Fortaleza. Destaca-se pelas praias de Cumbuco e Icaraí, polos de turismo e esportes aquáticos.",
    gentilico: "Caucaiense",
    prefeito: "Naumi Amorim",
    prefeituraUrl: "https://www.caucaia.ce.gov.br",
    prefeituraTelefone: "(85) 3342-1044",
    prefeituraEmail: "gabinete@caucaia.ce.gov.br",
    prefeituraHorario: "Seg a Sex, 8h às 17h",
    prefeituraEndereco: "Rua Coronel Correia, S/N - Centro, Caucaia - CE",
    prefeituraCnpj: "07.598.626/0001-90",
    brasaoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Bras%C3%A3o_de_Caucaia.png/150px-Bras%C3%A3o_de_Caucaia.png",
    bairros: [
      { nome: "Centro", cep: "61600-000", tipo: "urbano" },
      { nome: "Jurema", cep: "61610-000", tipo: "urbano" },
      { nome: "Parque Soledade", cep: "61611-000", tipo: "urbano" },
      { nome: "Marechal Rondon", cep: "61612-000", tipo: "urbano" },
      { nome: "Nova Metrópole", cep: "61613-000", tipo: "urbano" },
      { nome: "Araturi", cep: "61614-000", tipo: "urbano" },
      { nome: "Tabapuá", cep: "61615-000", tipo: "urbano" },
      { nome: "Parque Iracema", cep: "61616-000", tipo: "urbano" },
      { nome: "Guadalajara", cep: "61617-000", tipo: "urbano" },
      { nome: "Itambé", cep: "61618-000", tipo: "urbano" },
      { nome: "Padre Júlio Maria", cep: "61619-000", tipo: "urbano" },
      { nome: "Parque Potira", cep: "61620-000", tipo: "urbano" },
      { nome: "Icaraí", cep: "61627-000", tipo: "urbano" },
      { nome: "Cumbuco", cep: "61619-100", tipo: "urbano" },
      { nome: "Tabuba", cep: "61619-200", tipo: "urbano" },
      { nome: "Pacheco", cep: "61621-000", tipo: "urbano" },
      { nome: "Grilo", cep: "61622-000", tipo: "urbano" },
      { nome: "Capuan", cep: "61623-000", tipo: "urbano" },
      { nome: "Croatá", cep: "61624-000", tipo: "urbano" },
      { nome: "Sítios Novos", cep: "61650-000", tipo: "rural" },
      { nome: "Catuana", cep: "61651-000", tipo: "rural" },
      { nome: "Mirambé", cep: "61652-000", tipo: "rural" },
      { nome: "Tucunduba", cep: "61653-000", tipo: "rural" },
      { nome: "Bom Princípio", cep: "61654-000", tipo: "rural" },
      { nome: "Guararu", cep: "61655-000", tipo: "rural" },
    ],
    ruasPrincipais: [
      { nome: "Rua Coronel Correia", bairro: "Centro", cep: "61600-000" },
      { nome: "Rua Padre José Holanda", bairro: "Centro", cep: "61600-100" },
      { nome: "Avenida Dom Almeida Lustosa", bairro: "Centro", cep: "61600-200" },
      { nome: "Rua da Jurema", bairro: "Jurema", cep: "61610-100" },
      { nome: "Rua São Francisco", bairro: "Jurema", cep: "61610-200" },
      { nome: "Rua da Soledade", bairro: "Parque Soledade", cep: "61611-100" },
      { nome: "Avenida Marechal Rondon", bairro: "Marechal Rondon", cep: "61612-100" },
      { nome: "Rua Nova Metrópole", bairro: "Nova Metrópole", cep: "61613-100" },
      { nome: "Rua do Araturi", bairro: "Araturi", cep: "61614-100" },
      { nome: "Rua Tabapuá", bairro: "Tabapuá", cep: "61615-100" },
      { nome: "Rua Iracema", bairro: "Parque Iracema", cep: "61616-100" },
      { nome: "Rua Guadalajara", bairro: "Guadalajara", cep: "61617-100" },
      { nome: "Rua Itambé", bairro: "Itambé", cep: "61618-100" },
      { nome: "Rua Padre Júlio Maria", bairro: "Padre Júlio Maria", cep: "61619-100" },
      { nome: "Rua Potira", bairro: "Parque Potira", cep: "61620-100" },
      { nome: "Avenida Litorânea", bairro: "Icaraí", cep: "61627-100" },
      { nome: "Rua da Praia de Cumbuco", bairro: "Cumbuco", cep: "61619-110" },
      { nome: "Rua da Tabuba", bairro: "Tabuba", cep: "61619-210" },
      { nome: "Rua do Pacheco", bairro: "Pacheco", cep: "61621-100" },
      { nome: "Rua do Grilo", bairro: "Grilo", cep: "61622-100" },
      { nome: "Rua do Capuan", bairro: "Capuan", cep: "61623-100" },
      { nome: "Rua do Croatá", bairro: "Croatá", cep: "61624-100" },
      { nome: "Rua de Sítios Novos", bairro: "Sítios Novos", cep: "61650-100" },
      { nome: "Rua de Catuana", bairro: "Catuana", cep: "61651-100" },
      { nome: "Rua de Guararu", bairro: "Guararu", cep: "61655-100" },
    ],
    distritos: ["Sítios Novos", "Catuana", "Mirambé", "Tucunduba", "Bom Princípio", "Guararu"],
  },
];

export const newsData = [
  {
    id: 1,
    titulo: "Prefeitura anuncia reforma da praça central",
    resumo: "Obras devem começar no próximo mês com investimento de R$ 2 milhões para revitalização completa da área.",
    fonte: "Diário do Nordeste",
    tempo: "2h atrás",
    categoria: "Cidade",
  },
  {
    id: 2,
    titulo: "Festival cultural movimenta a economia local",
    resumo: "Evento reúne artistas regionais e atrai visitantes de todo o estado durante o fim de semana.",
    fonte: "O Povo Online",
    tempo: "4h atrás",
    categoria: "Cultura",
  },
  {
    id: 3,
    titulo: "Nova escola técnica será inaugurada em março",
    resumo: "Unidade oferecerá cursos profissionalizantes gratuitos para jovens da região.",
    fonte: "G1 Ceará",
    tempo: "6h atrás",
    categoria: "Educação",
  },
  {
    id: 4,
    titulo: "Campanha de vacinação atinge meta no município",
    resumo: "Mais de 90% da população-alvo foi imunizada contra a gripe nesta temporada.",
    fonte: "Tribuna do Ceará",
    tempo: "8h atrás",
    categoria: "Saúde",
  },
  {
    id: 5,
    titulo: "Safra recorde de castanha de caju na região",
    resumo: "Produtores celebram colheita abundante que fortalece a economia rural do município.",
    fonte: "Agência Brasil",
    tempo: "12h atrás",
    categoria: "Economia",
  },
];
